import 'package:magazine_luiza/models/product.dart';

List<Product> listOfproducts = [
  Product(
    photos: "assets/images/celular.jpg",
    name: "Smartphone Samsung Galaxy A71 128GB AZUl 6GB RAM",
    descrition: "Tela 6.7 Câm.Quadrupla Câm.+Selfie 32MP",
    price: "1.979,97",
    plots: "10x de",
    value: "212,90 sem juros",
    islove: false,
  ),
  Product(
    photos: "assets/images/geladeira.jpg",
    name: "Geladeira Brastemp Frost Free Duplex Evox",
    descrition: "375L BRM45 HKANA",
    price: "2.698,00",
    plots: "10x de",
    value: "269,80 sem juros",
    islove: false,
  ),
  Product(
    photos: "assets/images/fritadeira.jpg",
    name: "Fritadeira Elétrica sem Óleo/Air Fryer Nell Smart",
    descrition: "Preta 2,4L com Timer",
    price: "229,90",
    plots: "5x de",
    value: "45,98 sem juros",
    islove: false,
  ),
  Product(
    photos: "assets/images/computador.jpg",
    name: "Pc Gamer Neologic Start NLI81426 Ryzen 3 2200G 8GB",
    descrition: "Radeon Vega 8 integrado + SSD 240GB",
    price: "4.859,00",
    plots: "12x de",
    value: "404,92 sem juros",
    islove: false,
  ),
  Product(
    photos: "assets/images/microfone.jpg",
    name: "Microfone de Mesa Condensador para Celular,Computador e Notebook",
    descrition: "Redshock",
    price: "99,90",
    plots: "3x de",
    value: "33,30 sem juros",
    islove: false,
  ),
  Product(
    photos: "assets/images/ventilador.jpg",
    name: "Ventilador de Parede e Mesa Mondial Maxi Power",
    descrition: "NV-15-6P-FB 30cm 3 Velocidades",
    price: "89,90",
    plots: "2x de",
    value: "44,95 sem juros",
    islove: false,
  ),
  Product(
    photos: "assets/images/drone.jpg",
    name: "Drone Multilaser Eagle FPV",
    descrition: "Câmera HD Flips 360",
    price: "1.979,97",
    plots: "10x de",
    value: "212,90 sem juros",
    islove: false,
  ),
];
